name: ECR
run-name: ${{ github.actor }} is pushing an image to ECR
on:
  push:
    branches:
      - 'main'
permissions: 
  contents: read
  packages: write 
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/cicd_server:latest
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cicd_server:latest
      
   