name: ECR
run-name: ${{ github.actor }} is pushing an image to ECR
on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event name ${{ github.event_name }}"
      - run: echo "OS ${{ runner.os }}"
      - run: echo "Branch ${{ github.ref }} in repository ${{ github.repository }}"
      - name: checkout
        uses: actions/checkout@v3
      # - run: |
      #   docker-compose build
   